### ISSUE TITLE
Can't subscribe with a ssl connection on server

### ISSUE THREAD

**Issue by alissonpelizaro** [walkor/phpsocket.io-emitter#2]
Hello!

I'm trying to use this class in a secure Socket with SSL, but the method **stream_socket_client()** on line 25 persists to ask a valid certificate to subscribe in the server and I cant to solve this.

We don't need a certificate to connect as client. Isn't it? All the others clients from Socket.io.js don't use certificate and works fine.

Thanks a lot!

**Comment by walkor** [comment]
Show your codes please.

**Comment by alissonpelizaro** [comment]
@walkor thanks for your reply.

I can solve the `Certificate error` replacing the `line 25 of Emitter.php` with the following code:

```php
$ctx = stream_context_create([
  'ssl' => [
    'verify_peer' => false,
    'verify_peer_name' => false,
    'allow_self_signed' => false
  ]
]);
$this->_client = stream_socket_client(
  "ssl://{$this->_remoteIp}:{$this->_remotePort}",
  $errno,
  $errmsg,
  3,
  STREAM_CLIENT_CONNECT | STREAM_CLIENT_PERSISTENT,
  $ctx
);
```

Now I don't have more exceptions errors, but I still cannot connect on the server. See my code below:

**Server:** 
```php
require_once '../vendor/autoload.php';
use Workerman\Worker;
use Workerman\WebServer;
use Workerman\Autoloader;
use PHPSocketIO\SocketIO;

// ssl context
$context = array(
  'ssl' => array(
    'local_cert'  => '/etc/letsencrypt/live/secure/cert.pem',
    'local_pk'    => '/etc/letsencrypt/live/secure/privkey.pem',
    'verify_peer' => false,
  )
);
$io = new SocketIO(2021, $context);
$socket = new SockServer();
    
$io->on('connection', function($socket){
  echo "[info]: New conextion (".$socket->id.")\n";

  $socket->on('alert', function ($data)use($socket){
    echo "I received an alert! \n";
  });
});

Worker::runAll();
```

**Client Socket.io.js:** (working)
```php
var hostname = "https://myurl.com:2021";
var socket = io.connect(hostname, {
  secure: true,
  reconnect: true,
  rejectUnauthorized : false
});
socket.on('connect', function () {
  socket.emit("alert", 'I am sending an alert!');

  socket.on('disconnect', function () {
    console.log('disconnected');
  });
});
```

**Client Emitter:**  (not work)
```php
require_once 'vendor/autoload.php';

$emitter = new Emitter('localhost', 2021);
$emitter->emit('alert', 'I am sending an alert!');
echo 'Sent';
```

On the browser I dont have errors, but on the socket console I dont received the new conection

**Comment by walkor** [comment]
You run to the wrong way.
See https://github.com/walkor/phpsocket.io/issues/23

You lost codes 
```php
// =======Channel server========
$channel = new Channel\Server();
...
// ========ChannelAdapter========
$io->on('workerStart', function()use($io){
    $io->adapter('\PHPSocketIO\ChannelAdapter');
});
```
And the arguments `$port` for `Emitter($ip, $port)` is not the port of SocketIO but `Channel\Server()`'s which is 2206 by default.

So you do not need to change any source codes for line 25 of Emitter.php.

**Comment by alissonpelizaro** [comment]
@walkor once again thanks a lot for you reply.

I still cannot receive by server the alert sent from Emitter(). Can you see what I'm doing wrong now, please? I can't to solve this... The Emitter don't show any exception error.

This is whole my code:

**Server:**
```php
require_once '../vendor/autoload.php';
use Workerman\Worker;
use Workerman\WebServer;
use Workerman\Autoloader;
use PHPSocketIO\SocketIO;

$channel = new Channel\Server();
$io = new SocketIO(2021);

$io->on('workerStart', function()use($io){
  $io->adapter('\PHPSocketIO\ChannelAdapter');
});

$io->on('connection', function($socket){
  echo "New connection [$socket->id]\n";

  $socket->on('alert', function ($data)use($socket){
    echo "I received!\n";
  });

});
Worker::runAll();
```
_*I received the alert sent by socketio.js clients_

**Client Emitter:**
```php
require_once 'vendor/autoload.php';
$emitter = new Emitter();
$emitter->emit('alert', 'I sent!');
```
**Workerman state:**
![image](https://user-images.githubusercontent.com/26612874/57704542-800b9680-7638-11e9-8ea7-734a9b5de18b.png)

**Comment by walkor** [comment]
Emitter does not trigger SockeIO's server side events, only client's side events.

**Comment by alissonpelizaro** [comment]
@walkor, now I understood how it works! I was thinking that the Emmiter() starts a connection as client with the Server. I had some trouble because I don't speak english and this is my first time working with sockets.

Congratulations for your projects and thank you very much for all your help.

God blesses.

**Comment by walkor** [comment]
I'm not speak english too. 🤝
You are welcome.
